-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgVxJi4MATOF1piOB5
ISQPenkey+10j6snLRXKRi2Bz1ygCgYIKoZIzj0DAQehRANCAASRXbeO/6GUvxPq
Y8s1oNtgQRcxHINp3NlLrk2VVFY97OdEPR9/CmLoFuhp9RlllxGPXj/6UJa8gyeq
KGpgPlco
-----END PRIVATE KEY-----