/**
 * Ported from Pabloddc16/Mundial2026 src/swap-qr.js — same wire format
 * so codes generated by the web reference and our mobile app are
 * interoperable.
 */
import LZString from 'lz-string'

const VERSION = 1
const PREFIX_PLAIN = 'M26:'
const PREFIX_COMPRESSED = 'M26Z:'
const MAX_PLAIN_LEN = 1024

export const SWAP_VERSION = VERSION

export interface OfferPayload {
  v: number
  t: 'o'
  u: string
  r: string[]
  n?: string[]
  dn?: string
  av?: string
}

export interface ReceiptPayload {
  v: number
  t: 'r'
  u: string
  k: string[]
  g: string[]
  dn?: string
}

export type SwapPayload = OfferPayload | ReceiptPayload

export function encodeOffer(input: {
  username: string
  repetidas: string[]
  faltantes?: string[]
  name?: string
  avatar?: string
}): string {
  const p: OfferPayload = {
    v: VERSION,
    t: 'o',
    u: input.username || 'anon',
    r: [...(input.repetidas ?? [])],
  }
  if (input.faltantes && input.faltantes.length) p.n = input.faltantes
  if (input.name) p.dn = input.name
  if (input.avatar) p.av = input.avatar
  return encodePayload(p)
}

export function encodeReceipt(input: {
  username: string
  took: string[]
  gave: string[]
  name?: string
}): string {
  const p: ReceiptPayload = {
    v: VERSION,
    t: 'r',
    u: input.username || 'anon',
    k: [...(input.took ?? [])],
    g: [...(input.gave ?? [])],
  }
  if (input.name) p.dn = input.name
  return encodePayload(p)
}

function encodePayload(payload: SwapPayload): string {
  const json = JSON.stringify(payload)
  if (json.length <= MAX_PLAIN_LEN) return PREFIX_PLAIN + encodeURIComponent(json)
  return PREFIX_COMPRESSED + LZString.compressToEncodedURIComponent(json)
}

export function decodePayload(raw: string): SwapPayload | null {
  if (typeof raw !== 'string') return null
  const text = raw.trim()
  let json: string | null = null
  if (text.startsWith(PREFIX_COMPRESSED)) {
    try { json = LZString.decompressFromEncodedURIComponent(text.slice(PREFIX_COMPRESSED.length)) } catch { return null }
  } else if (text.startsWith(PREFIX_PLAIN)) {
    try { json = decodeURIComponent(text.slice(PREFIX_PLAIN.length)) } catch { return null }
  } else {
    return null
  }
  if (!json) return null
  let p: unknown
  try { p = JSON.parse(json) } catch { return null }
  if (!p || typeof p !== 'object') return null
  const rec = p as Record<string, unknown>
  if (rec.v !== VERSION) return null
  if (rec.t !== 'o' && rec.t !== 'r') return null
  if (typeof rec.u !== 'string' || !rec.u) return null
  if (rec.t === 'o' && !Array.isArray(rec.r)) return null
  if (rec.t === 'r' && (!Array.isArray(rec.k) || !Array.isArray(rec.g))) return null
  return p as SwapPayload
}
